TestTask_InfTech/Areas/FileStorageArea/Controllers/FoldersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestTask_InfTech.DB;
using TestTask_InfTech.DB.Model;
using TestTask_InfTech.ViewModels;

namespace TestTask_InfTech.Areas.FileStorageArea.Controllers
{
    [Area("FileStorageArea")]
    public class FoldersController : Controller
    {
        private const string csSystemSeparator = "\\";
        private readonly FileStorageDB _context;
        private const string SessionCurrentFolderGuid = "CurrentFolderGuid";
        private const string SessionCurrentElementGuid = "CurrentElementGuid";

        private string projectRootPath;
        private string outputPath;
        private string storagePath;

        public FoldersController(FileStorageDB aContext)
        {
            _context = aContext;

            projectRootPath = AppDomain.CurrentDomain.BaseDirectory;
            outputPath = Path.Combine(projectRootPath, "wwwroot/Content");
            storagePath = Path.Combine(projectRootPath, "storage");
        }

        // GET: FileStorageArea/Folders
        public async Task<IActionResult> Index()
        {
            ViewBag.CurrentFolderElement = HttpContext.Session.GetString(SessionCurrentFolderGuid) ?? string.Empty;
            ViewBag.CurrentElement = HttpContext.Session.GetString(SessionCurrentElementGuid) ?? string.Empty;

            //начнем с обработки корневых папок
            var tmpFolders = await _context.Folder.Where(a => a.Parental == null).ToListAsync();
            var tmpSubNodeModels = new List<SubNodeModel>();
            var tmpFoldersGuid = new List<Guid>();
            var tmpFilesGuid = new List<Guid>();

            _ = await _context.Ext.ToListAsync();

            await PrepareSubNode(tmpFolders, tmpSubNodeModels, tmpFoldersGuid, tmpFilesGuid);

            return View("IndexTree", tmpSubNodeModels);
        }

        private async Task PrepareSubNode(List<Folder> aFolders, List<SubNodeModel> aSubNodeModels, List<Guid> aFoldersGuid, List<Guid> aFilesGuid)
        {
            foreach (var tmpFolder in aFolders)
            {
                //папка уже обработана
                if (aFoldersGuid.Contains(tmpFolder.FolderId))
                    continue;

                //папку начали обрабатывать
                aFoldersGuid.Add(tmpFolder.FolderId);

                var tmpSubFolders = await _context.Folder.Where(a => (a.Parental != null) && (a.Parental.FolderId.Equals(tmpFolder.FolderId))).ToListAsync();
                List<SubNodeModel> tmpSubNodeModels = new List<SubNodeModel>();

                await PrepareSubNode(tmpSubFolders, tmpSubNodeModels, aFoldersGuid, aFilesGuid);

                //создадим обьект дерева
                var tmpNode = new SubNodeModel()
                {
                    ChildrenFolder = tmpSubNodeModels,
                    CurrentFolder = tmpFolder,
                };
                var tmpChildrenFile = await _context.Files.Where(a => a.Folder.FolderId.Equals(tmpFolder.FolderId) && a.Extension != null).ToListAsync();
                tmpNode.ChildrenFile = tmpChildrenFile;

                aSubNodeModels.Add(tmpNode);
            }
        }

        // GET: FileStorageArea/Folders/Choice/5
        public IActionResult Choice(Guid? aId)
        {
            //            ViewBag.CurrentFileElement = aId.ToString();
            ViewBag.CurrentElement = aId.ToString();

            HttpContext.Session.SetString(SessionCurrentFolderGuid, aId.ToString() ?? string.Empty);
            ViewBag.CurrentFolderElement = aId.ToString();

            return RedirectToAction("Index");
        }

        // GET: FileStorageArea/Folders/Details/5
        public async Task<IActionResult> Details(Guid? aId)
        {
            if (aId == null)
            {
                return NotFound();
            }

            var tmpFolder = await _context.Folder
                .FirstOrDefaultAsync(m => m.FolderId == aId);
            if (tmpFolder == null)
            {
                return NotFound();
            }

            return View(tmpFolder);
        }

        // GET: FileStorageArea/Folders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FileStorageArea/Folders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FolderId,Name")] Folder aFolder)
        {
            if (ModelState.IsValid)
            {
                aFolder.FolderId = Guid.NewGuid();
                //подключение родительской папки
                var tmpCurrentFolderId = HttpContext.Session.GetString(SessionCurrentFolderGuid) ?? string.Empty;
                if (!tmpCurrentFolderId.Equals(string.Empty))
                {
                    aFolder.Parental = await _context.Folder.Where(a => a.FolderId.ToString().Equals(tmpCurrentFolderId)).FirstOrDefaultAsync();
                }

                await CreateFolderAsync(aFolder);

                //перевод на вновь созданную папку
                HttpContext.Session.SetString(SessionCurrentFolderGuid, aFolder.FolderId.ToString());
                HttpContext.Session.SetString(SessionCurrentElementGuid, aFolder.FolderId.ToString());

                _context.Folder.Add(aFolder);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(aFolder);
        }

        private async Task<bool> CreateFolderAsync(Folder aFolder)
        {
            var tmpFolderPath = await GetRealFolderPathAsync(aFolder, aFolder.Name);

            string tmpBaseStr = AppDomain.CurrentDomain.BaseDirectory;

            var tmpFullServerPath = string.Format("{1}{0}", tmpFolderPath, tmpBaseStr);
            var tmpDirectory = System.IO.Directory.CreateDirectory(tmpFullServerPath);
            if (tmpDirectory.Exists)
                return true;

            return false;
        }

        private async Task<string> GetRealFolderPathAsync(Folder aFolder, string aPath)
        {
            //путь уже вычислен до корня
            if (aFolder.Parental == null)
                return aPath;

            //получим папку верхнего уровня относительно текущей
            var tmpPath = string.Format("{2}{1}{0}", aPath, csSystemSeparator, aFolder.Parental.Name);
            return await GetRealFolderPathAsync(aFolder.Parental, tmpPath);
        }

        // GET: FileStorageArea/Folders/Edit/5
        public async Task<IActionResult> Edit(Guid? aId)
        {
            if (aId == null)
            {
                return NotFound();
            }

            var tmpFolder = await _context.Folder.FindAsync(aId);
            if (tmpFolder == null)
            {
                return NotFound();
            }
            return View(tmpFolder);
        }

        // POST: FileStorageArea/Folders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid aId, [Bind("FolderId,Name")] Folder aFolder)
        {
            if (aId != aFolder.FolderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Folder.Update(aFolder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FolderExists(aFolder.FolderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aFolder);
        }

        // GET: FileStorageArea/Folders/Delete/5
        public async Task<IActionResult> Delete(Guid? aId)
        {
            if (aId == null)
            {
                //TODO продумать отображения под некорректные аргументы, подать пользователю больше информации о текущих действиях
                return RedirectToAction("Index");
                //                return NotFound();
            }

            var tmpFolder = await _context.Folder
                .FirstOrDefaultAsync(m => m.FolderId == aId);
            if (tmpFolder == null)
            {
                return NotFound();
            }

            return View(tmpFolder);
        }

        // POST: FileStorageArea/Folders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid aId)
        {
            var tmpFolder = await _context.Folder.FindAsync(aId);
            if (tmpFolder != null)
            {
                await DeleteAllFilesAsync(tmpFolder);
                await DeleteFilesAsync(tmpFolder);

                await DeleteAllFoldersAsync(tmpFolder);
                await DeleteFolderAsync(tmpFolder);

                _context.Folder.Remove(tmpFolder);

                await _context.SaveChangesAsync();

                HttpContext.Session.SetString(SessionCurrentFolderGuid, string.Empty);
                HttpContext.Session.SetString(SessionCurrentElementGuid, string.Empty);
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Удаление папки
        /// </summary>
        /// <param name="aFolder"></param>
        /// <returns></returns>
        private async Task<bool> DeleteFolderAsync(Folder aFolder)
        {

TestTask_InfTech/Areas/FileStorageArea/Views/Shared/_Layout.cshtml
@{
    var currentId = @ViewBag.CurrentFolderElement;
    var currentFileId = @ViewBag.CurrentFileElement;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTask_InfTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTask_InfTech.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTask_InfTech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageAreas" asp-controller="FileStorage" asp-action="Index">Test Task</a>
                        </li>
                        @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="Create">Create Folder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="Delete" asp-route-aid="@currentId">Delete Folder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="Edit" asp-route-aid="@currentId">Rename Folder</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="SingleFileUpload" asp-route-aid="@currentId">Upload File</a>
                        </li>
                        <!-- TODO доработать не сделанные действия, в зависимости от выбранного элемента разблокировать доступные элементы в меню-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="DownloadFile">Download File</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="DeleteFile">Delete File</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="FileStorageArea" asp-controller="Folders" asp-action="EditFile">Rename File</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TestTask_InfTech - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>